baseURL: ""
languageCode: "en-us"
title: "Remote Newbie"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsstyle: "monokai"
paginate: 6
social:
  twitter: "https://twitter.com/remotenewbie"
  instagram: "https://instagram.com/remoteindy"
  youtube: "https://www.youtube.com/channel/UCh1t4RdWMZ2mfYTWfpFaZNg"
  facebook: "https://www.facebook.com/remotenewbie/"
  patreon: ""
taxonomies:
  author: authors
ga_analytics: "#"
