baseURL: ""
languageCode: "en-us"
title: "Cafecito Blog"
disableKinds: ["taxonomy", "taxonomyTerm"]
pygmentsstyle: "monokai"
paginate: 6
social:
  twitter: "https://twitter.com/meetcafecito"
  instagram: "https://instagram.com/meetcafecito"
  youtube: ""
  facebook: "https://www.facebook.com/meetcafecito/"
  patreon: ""
taxonomies:
  author: authors
ga_analytics: "#"
